spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: springuser
    password: springuser
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true